### ISSUE TITLE
No changes made to file system, no error message given

### ISSUE THREAD

**Issue by kropper** [abaldwin88/roamer#19]
On macOS (Sierra), roamer installs successfully with sudo pip3 install roamer. Running `roamer`, $EDITOR properly opens with the list of files and hashes; after making any changes (renaming, copying, etc.) and saving/quitting, there is no error message given, but none of the edits has any effects, i.e., the file system is completely unchanged. Is there any way to debug this, e.g., by enabling a verbose output to see whether roamer detects the changes properly?

Bug Report Template

**Comment by abaldwin88** [comment]
What editor are you using?

On Aug 31, 2017 11:42 AM, "kropper" <notifications@github.com> wrote:

On macOS (Sierra), roamer installs successfully with sudo pip3 install
roamer. Running roamer, $EDITOR properly opens with the list of files and
hashes; after making any changes (renaming, copying, etc.) and
saving/quitting, there is no error message given, but none of the edits has
any effects, i.e., the file system is completely unchanged. Is there any
way to debug this, e.g., by enabling a verbose output to see whether roamer
detects the changes properly?

Bug Report Template
roamer version: 0.2.0 OS: Darwin Kernel Version 16.7.0 (macOS Sierra) Python
version: 3.6.2 Steps to reproduce (start with removing ~/.roamer-data): As
described above, happens on first use after installation and afterwards.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abaldwin88/roamer/issues/19>, or mute the thread

**Comment by kropper** [comment]
Using neovim nvim v0.2.0 (installed via Homebrew)

**Comment by abaldwin88** [comment]
Can you give me the full printout of what $EDITOR is set to?

**Comment by kropper** [comment]
```
$echo $EDITOR
/Users/kropper/bin/homebrew-links/nvim
```

**Comment by abaldwin88** [comment]
ah ok this is likely caused by #13. 

As a temporary fix you should be able to run:

```
alias nvim=/Users/kropper/bin/homebrew-links/nvim
export ROAMER_EDITOR=nvim
```

**Comment by kropper** [comment]
cheers mate, that's it. thanks!
